version: "3"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      N8N_BASIC_AUTH_ACTIVE: "false"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      WHATSAPP_TOKEN: "${WHATSAPP_TOKEN}"
      WHATSAPP_PHONE_NUMBER_ID: "${WHATSAPP_PHONE_NUMBER_ID}"
      N8N_USER_EMAIL: "${N8N_USER_EMAIL}"
      N8N_USER_FIRST_NAME: "${N8N_USER_FIRST_NAME}"
      N8N_USER_LAST_NAME: "${N8N_USER_LAST_NAME}"
      N8N_USER_PASSWORD: "${N8N_USER_PASSWORD}"
      WEBHOOK_URL: "http://localhost:5678/"
      GENERIC_TIMEZONE: "America/Argentina/Buenos_Aires"
    volumes:
      - ~/.n8n:/home/node/.n8n
